name: GFCC_CI

on:
  push:
  pull_request:
  release:
  schedule:
    - cron: '0 0 * * SUN'
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        experimental: [false]
        mpi_impl:
          - openmpi
          - mpich
        armci_network:
          - mpi-pr
        cxx:
          - g++-9
        cc:
          - gcc-9
        fc:
          - gfortran-9
        include:
          - os: ubuntu-20.04
            experimental: true 
            mpi_impl: mpich
            armci_network: mpi-pr
            cxx: g++-10
            cc: gcc-10
            fc: gfortran-10
      fail-fast: false
    env:
        MPI_IMPL: ${{ matrix.mpi_impl }}
        PORT: ${{ matrix.armci_network }}
        CXX: ${{ matrix.cxx }}
        CC: ${{ matrix.cc }}
        FC: ${{ matrix.fc }}
        GFCC_SRC: ${HOME}/gfcc_src
        GFCC_INSTALL_PATH: ${HOME}/gfcc_install
    continue-on-error: ${{ matrix.experimental }}
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 40
      - name: Cache install steps
        id: gfcc-cache-install
        uses: actions/cache@v2
        env:
          cache-name: cache-install-steps
        with:
          # cache files are stored in `~/apps` on Linux/macOS
          path: |
            apps
          key: ${{ runner.os }}-${{ matrix.mpi_impl}}-${{ matrix.armci_network}}-${{ matrix.cc }}-${{ matrix.cxx }}-${{ matrix.config_opts}}-gfcc-v000

      - name: install_packages
        run: |
          case "${{ matrix.os }}" in
          ubuntu*|jessie|stretch|buster)
          sudo apt-get update -q -y
          if [[ "$mpi_impl" == "openmpi" ]] ; then mpi_bin="openmpi-bin" ; mpi_libdev="libopenmpi-dev" ;  fi
          if [[ "$mpi_impl" == "mpich" ]] ; then mpi_bin="mpich" ; mpi_libdev="libmpich-dev" ;  fi
          sudo apt-get install -q -y cmake "${mpi_bin}" "${mpi_libdev}" gfortran curl
          curl -LJO https://github.com/Kitware/CMake/releases/download/v3.18.4/cmake-3.18.4-Linux-x86_64.tar.gz
          tar xzf cmake-3.18.4-Linux-x86_64.tar.gz
          export PATH=`pwd`/cmake-3.18.4-Linux-x86_64/bin:$PATH
          ;;
          macos*)
          brew update
          brew install gcc openmpi cmake wget autoconf automake || true
          curl -LJO https://github.com/Kitware/CMake/releases/download/v3.18.4/cmake-3.18.4-Darwin-x86_64.tar.gz
          tar xzf cmake-3.18.4-Darwin-x86_64.tar.gz
          export PATH=`pwd`/cmake-3.18.4-Linux-x86_64/bin:$PATH
          ;;
          esac
      - name: before_compile
        if: steps.gfcc-cache-install.outputs.cache-hit != 'true'
        run: |
          pwd
          ls -lart
          mkdir -p $GITHUB_WORKSPACE/apps
      - name: compile_gfcc
        if: ${{ success() }}
        run: |
          export PATH=`pwd`/cmake-3.18.4-`uname -s`-x86_64/bin:$PATH
          cd ${GFCC_SRC}/contrib/TAMM 
          mkdir build && cd build
          cmake -DCMAKE_INSTALL_PREFIX=${GFCC_INSTALL_PATH} ..
          make -j2
          make install
          cd ${GFCC_SRC}
          mkdir build && cd build
          cmake -DCMAKE_INSTALL_PREFIX=${GFCC_INSTALL_PATH} ..
          make -j2
          make install
      - name: after_failure
        if: ${{ failure() }}
        run: |
          pwd
          ls -lart
          find . -name config.log -exec cat {} ";" || true
          echo '***** CMakeOutput.log *****'
          find . -name CMakeOutput.log -exec cat {} ";" || true
          echo '***** CMakeError.log ******'
          find . -name CMakeError.log  -exec cat {} ";" || true
      - name: qa_test
        id: qa_test
        if: steps.compile_gfcc.conclusion == 'success'
        run: |
          cd $GFCC_SRC/build
          export OMP_NUM_THREADS=1
          mpirun -n 4 ./test_stage/$GFCC_INSTALL_PATH/methods/GF_CCSD ../tests/co.json
